import {
    FaTachometerAlt,
    FaClipboardList,
    FaHistory,
    FaFileInvoiceDollar,
    FaUserCheck,
    FaMoneyCheckAlt,
    FaTasks,
    FaChartBar,
    FaDatabase,
    FaFileInvoice,
} from "react-icons/fa";

export const dummyMenu = [
    {
        id: 1,
        name: "Dashboard",
        path: "/dashboard",
        icon: FaTachometerAlt,
        // roles: [],
        submenu: [],
    },
    {
        id: 1,
        name: "Data Faktur",
        path: "/data-faktur",
        icon: FaFileInvoice,
        // roles: [],
        submenu: [],
    },
    {
        id: 2,
        name: "Daftar Tugas Harian",
        path: "/daftar-tugas-harian",
        icon: FaClipboardList,
        // roles: [],
        submenu: [],
    },
    {
        id: 3,
        name: "Riwayat Pengantaran",
        path: "/riwayat-pengantaran",
        icon: FaHistory,
        // roles: [],
        submenu: [],
    },
    {
        id: 4,
        name: "Bayar Faktur",
        path: "/bayar-faktur",
        icon: FaFileInvoiceDollar,
        // roles: [],
        submenu: [],
    },
    {
        id: 5,
        name: "Verifikasi Pembayaran",
        path: "/verifikasi-pembayaran",
        icon: FaMoneyCheckAlt,
        // roles: [],
        submenu: [],
    },
    {
        id: 6,
        name: "Penugasan Faktur",
        path: "/penugasan-faktur",
        icon: FaUserCheck,
        // roles: [],
        submenu: [],
    },
    {
        id: 7,
        name: "Monit. Penugasan",
        path: "/monitoring-penugasan",
        icon: FaTasks,
        // roles: [],
        submenu: [],
    },
    {
        id: 8,
        name: "Laporan",
        path: "/laporan",
        icon: FaChartBar,
        // roles: [],
        submenu: [],
    },
    {
        id: 9,
        name: "Data Master",
        path: "/data-master",
        icon: FaDatabase,
        // roles: [],
        submenu: [
            {
                name: "Data Pelanggan",
                path: "/data-pelanggan",
                // roles: [],
            },
        ],
    },
];